//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public long post_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string thumbnail { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
    
        public virtual user user { get; set; }
    }
}
